server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_secret?useUnicode=true&characterEncoding=utf-8&&serverTimezone=UTC
    username: root
    password: root
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    # 配置引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    root: info
