server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xujie.vip:3306/my_secret?useUnicode=true&characterEncoding=utf-8&&serverTimezone=UTC
    username: my_secret
    password: root
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    # 配置引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  profiles:
    active: dev

logging:
  level:
    root: info
  file:
    path: /var/log/my_secret/my_secret.log
mybatis:
  mapper-locations: classpath:/mapper/*.xml
my:
  secret:
#    server:
#      ip: http://164z53n749.iask.in
    wechat:
#      appid: wx1ac3362f8a49e7cc
#      appsecret: 373e5e95e6faaebd824949855b96703a
      ticketurl: https://api.weixin.qq.com/cgi-bin/ticket/getticket
      grantType: client_credential
    location:
      ip: http://api.cellocation.com:81/regeo/

